spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    password: 1234
    username: melina
  jpa:
    showSql: true
#    hibernate:
    properties:
      hibernate.format: true
#      ddl-auto:
      #create-drop #if run application it will create tables, if we stop it will drop.
      #update is another functionality
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        webAllowOthers: false

